### ISSUE TITLE
typo in CSS classes naming

### ISSUE THREAD

**Issue by long-lazuli** [ckeditor/ckeditor5-image#167] opened 2018-01-29 08:48 UTC
Refering to this document : https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines

There is a typo in those classes :  
https://github.com/ckeditor/ckeditor5-image/blob/master/theme/textalternativeform.css

I expect this selector `[class^='ck-']` to match every CKEditor UI.

**Comment by Reinmar** [comment] 2018-01-29 11:44
Thanks for noticing. We've got a ticket somewhere about reviewing these classes because there may be more of these.

**Comment by oleq** [comment] 2018-02-01 12:30
Duplicate of https://github.com/ckeditor/ckeditor5-ui/issues/112.

**Closed by oleq** 2018-02-01 12:30 UTC
Labels: status:confirmed, type:bug
